[versions]
antlr-kotlin = "1.0.8"
kotlin = "2.2.20"
kotlinx-io = "0.8.2"
ktlint = "1.7.1"

[plugins]
antlr-kotlin = { id = "com.strumenta.antlr-kotlin", version.ref = "antlr-kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.7" }
spotless = { id = "com.diffplug.spotless", version = "7.2.1" }

[libraries]
antlr-kotlin-runtime = { module = "com.strumenta:antlr-kotlin-runtime", version.ref = "antlr-kotlin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
