complexity:
  CyclomaticComplexMethod:
    active: false
  LargeClass:
    active: false
  LongMethod:
    active: false
  NestedBlockDepth:
    active: false
  TooManyFunctions:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
  ReturnCount:
    active: false
  WildcardImport:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
